### ISSUE TITLE
Windows, ever?

### ISSUE THREAD

**Issue by RdWing** [hattedsquirrel/ryzen_monitor#3]
Great work. I have been able to pull the relevant SMU data from my 5900x on windows using [SMUDebugTool](https://github.com/irusanov/SMUDebugTool), but it doesn't show labels, only offsets. Any plans to bring this to windows? There's still no other program for monitoring that reads out per core on Zen 3 for windows.
![image](https://user-images.githubusercontent.com/19214916/114251738-003af380-9957-11eb-997a-1592a36f8465.png)

**Comment by hattedsquirrel** [comment]
You can get per core statistics on temperature, frequency, c-states and power consumption from HWiNFO.
Right now I'm not working on a windows port myself. But I'm open to collaborate with anyone who is willing to put the necessary efford in creating a windows application.
