### ISSUE TITLE
get_processor_topology() does not return a value

### ISSUE THREAD

**Issue by tpoechtrager** [hattedsquirrel/ryzen_monitor#8]
https://github.com/hattedsquirrel/ryzen_monitor/blob/d153d4b5ef900a974262c35a07a334fdd88ec0de/src/readinfo.c#L85

It should be `void`.

**Comment by hattedsquirrel** [comment]
Indeed, thanks. Corrected in commit https://github.com/hattedsquirrel/ryzen_monitor/commit/90ee4c248bed2553cba2b59e69dddefb285f9168
